# terraform-repository.yaml
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformRepository
metadata:
  name: gcp-vm-repo
  namespace: burrito-system
spec:
  repository:
    url: "https://github.com/4emerson/terraform-gcp-vm.git"
    # secretName não necessário para repos públicos
  terraform:
    enabled: true
    version: "1.6.0"

---
# .burrito/burrito.yaml - versão básica primeiro
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformLayer
metadata:
  name: gcp-vm-layer
  namespace: burrito-system
spec:
  path: "."
  branch: "main"
  repository:
    name: gcp-vm-repo
    namespace: burrito-system
  remediationStrategy:
    autoApply: true
  overrideRunnerSpec:
    env:
      - name: "TF_VAR_project_id"
        value: "gcp-4linux"
      - name: "TF_VAR_ssh_public_key"
        valueFrom:
          secretKeyRef:
            name: "ssh-keys"
            key: "public_key"